repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo:  https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      args:
        - "--max-line-length=130"
        - "--ignore=E402,E501,W503,F401,F403"
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
